#########################
# build-system settings #
#########################

[build-system]
requires = [
    "scikit-build-core",
]
build-backend = "scikit_build_core.build"


####################
# project settings #
####################

[project]
name = "lofarbeam"
version = "0.0.0"  # Keep in sync with top-level `CMakeLists.txt` file
description = "lofarbeam"
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.9"
license = {text = "GPLv3+"}
authors = [
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Programming Language :: C++",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Astronomy",
]
dependencies = [
    "numpy",
    "python-casacore"
]

[project.urls]
Homepage = "https://github.com/cyriltasse/LOFARBeam"
Documentation = "https://github.com/cyriltasse/LOFARBeam"
Repository = "https://github.com/cyriltasse/LOFARBeam"


#########################
# cibuildwheel settings #
#########################

[tool.cibuildwheel]
build-verbosity = 1
## Build
before-all = "yum install -y boost-devel"
before-build = "pip install --upgrade pip; pip install oldest-supported-numpy"
build = "cp3{9,10,11,12,13}-*_x86_64"

[tool.cibuildwheel.linux]
skip = ["*-musllinux_*"]

[[tool.cibuildwheel.overrides]]
select="cp38-*"
manylinux-x86_64-image = "quay.io/casacore/casacore:py38_v3.7.1"

[[tool.cibuildwheel.overrides]]
select="cp39-*"
manylinux-x86_64-image = "quay.io/casacore/casacore:py39_v3.7.1"

[[tool.cibuildwheel.overrides]]
select="cp310-*"
manylinux-x86_64-image = "quay.io/casacore/casacore:py310_v3.7.1"

[[tool.cibuildwheel.overrides]]
select="cp311-*"
manylinux-x86_64-image = "quay.io/casacore/casacore:py311_v3.7.1"

[[tool.cibuildwheel.overrides]]
select="cp312-*"
manylinux-x86_64-image = "quay.io/casacore/casacore:py312_v3.7.1"

[[tool.cibuildwheel.overrides]]
select="cp313-*"
manylinux-x86_64-image = "quay.io/casacore/casacore:py313_v3.7.1"

#########################
# scikit-build settings #
#########################

[tool.scikit-build]
cmake.version = ">=3.15"
ninja.version = ">=1.5"
install.components = ["libraries", "headers"]
logging.level = "INFO"
metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"
sdist.exclude = [".github", ".gitignore"]
#sdist.include = ["casacore/_version.py"]
wheel.packages = ["python-casacore"]

[tool.scikit-build.cmake.define]
BUILD_PYTHON = "ON"
