name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel for ${{matrix.python.cp}}-${{matrix.buildplat.sys}}
          ${{matrix.buildplat.arch}}
    runs-on: ${{ matrix.buildplat.runs_on }}
    strategy:
      matrix:
        buildplat:
        - { runs_on: ubuntu-20.04, sys: manylinux, arch: x86_64 }
        python:
        - { cp: "cp39",   rel: "3.9" }
        - { cp: "cp310",  rel: "3.10" }
        - { cp: "cp311",  rel: "3.11" }
        - { cp: "cp312",  rel: "3.12" }
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.0
        env:
          CIBW_BUILD: ${{ matrix.python.cp }}-${{ matrix.buildplat.sys }}*
          CIBW_ARCHS: ${{ matrix.buildplat.arch }}
        #   CIBW_SOME_OPTION: value
        #   ...
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
            name: ${{matrix.python.cp}}-${{matrix.buildplat.sys}}-${{matrix.buildplat.arch}}
            path: wheelhouse/*
