name: Release Binaries
on:
  push:
    tags:
      - '*'

permissions:
    contents: write
    packages: write
    id-token: write
    attestations: write

jobs:
  release:
    name: Make release
    runs-on: ${{ matrix.buildplat.runs_on }}
    strategy:
      matrix:
        buildplat:
        - { runs_on: ubuntu-latest, sys: manylinux, arch: x86_64 }
        python:
        #- { cp: "cp39",   rel: "3.9" }
        - { cp: "cp310",  rel: "3.10" }
        #- { cp: "cp311",  rel: "3.11" }
        #- { cp: "cp312",  rel: "3.12" }
    # https://trstringer.com/github-actions-create-release-upload-artifacts/
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --draft \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.0
        env:
          CIBW_BUILD: ${{ matrix.python.cp }}-${{ matrix.buildplat.sys }}*
          CIBW_ARCHS: ${{ matrix.buildplat.arch }}
        #   CIBW_SOME_OPTION: value
        #   ...
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      #- name: Upload Artifacts
      #  uses: actions/upload-artifact@v4
      #  with:
      #      name: ${{matrix.python.cp}}-${{matrix.buildplat.sys}}-${{matrix.buildplat.arch}}
      #      path: wheelhouse/*
      #- uses: actions/download-artifact@v8
      #  with:
      #    #path: 
      #    merge-multiple: true
      - name: Display structure of downloaded files
        run: ls -R

      - name: Upload assets
        uses: alexellis/upload-assets@0.4.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_paths: '["./wheelhouse/*.whl"]'
